### ISSUE TITLE
functional tests are failing on 'shell to vm' 

### ISSUE THREAD

**Issue by nvgoldin** [lago-project/lago#399]
The CirrOS VM doesn't get an IP, logging in with lago console and executing ```/etc/init.d/S40network restart``` resolves the issue. The only change done to automation was https://github.com/lago-project/lago/commit/afec1ac3042adb62678e0940fd2289226e9aa129, could it be that ``dnsmasq`` is not yet configured when we run ``lago start``(now with KVM enabled it is probably done faster than before)? @david-caro - any ideas?

**Comment by mykaul** [comment]
I would say that this is exactly why we need to make some order between SSH and root passwords, between password-based and public-key based authentication. We need to see that such a VM:
1. Does have a root password (for ovirt-system-tests use case)
2. Does have a SSH password (which happens of course to be the root password) - for Lago to connect to it.
3. Does not have a SSH public key (we do not inject to it a public key - note that ovirt-system-tests might in the future via cloud-init

Currently, there's quite a bit of a mixup. It's very similar to the situation with Hosted-Engine.

**Comment by gbenhaim** [comment]
We've already experienced this issue before: https://github.com/lago-project/lago/pull/318
The interface is shown in the vm, but for some reason ifup/ifdown can't recognize it.  I don't think that this issue relates to ssh but also don't have a good explanation why it relates to the boot menu.

**Comment by mykaul** [comment]
On Thu, Dec 22, 2016 at 5:50 PM, Gal Ben Haim <notifications@github.com>
wrote:

> We've already experienced this issue before: #318
> <https://github.com/lago-project/lago/pull/318>
> The interface is shown in the vm, but for some reason ifup/ifdown can't
> recognize it. I don't think that this issue relates to ssh but also don't
> have a good explanation why it relates to the boot menu.
>

Reminds me of an infamous issue in OpenStack - the network (and
specifically, the DHCP services) are not fast enough to be up and running
before the VM is already requesting the network.
Y.

**Comment by gbenhaim** [comment]
As I see it we have two options:
1. Enable the boot menu.
2. Search for another image to use in the functional tests.

@mykaul @nvgoldin @ifireball @david-caro 
Thoughts ?

**Comment by mykaul** [comment]
I've opened a bug on libvirt on the issue.
Y.

**Comment by nvgoldin** [comment]
I looked at dnsmasq logs:

```
Dec 25 07:54:57 ng-lt dnsmasq-dhcp[4624]: DHCP, IP range 192.168.201.100 -- 192.168.201.254, lease time 1h
Dec 25 07:54:57 ng-lt dnsmasq-dhcp[4624]: DHCPv6, IP range fd8f:1391:3a82:5e0d::c0a8:c964 -- fd8f:1391:3a82:5e0d::c0a8:c9fe, lease time 1h
Dec 25 07:54:57 ng-lt dnsmasq-dhcp[4624]: router advertisement on fd8f:1391:3a82:5e0d::
Dec 25 07:54:57 ng-lt dnsmasq-dhcp[4624]: IPv6 router advertisement enabled
Dec 25 07:54:57 ng-lt dnsmasq-dhcp[4624]: DHCP, sockets bound exclusively to interface 71b4-785d519
Dec 25 07:54:57 ng-lt dnsmasq[4624]: reading /etc/resolv.conf
Dec 25 07:54:57 ng-lt dnsmasq[4624]: using nameserver 10.35.255.14#53
Dec 25 07:54:57 ng-lt dnsmasq[4624]: using nameserver 10.38.5.26#53
Dec 25 07:54:57 ng-lt dnsmasq[4624]: using nameserver 10.200.0.246#53
Dec 25 07:54:57 ng-lt dnsmasq[4624]: using nameserver 10.192.206.245#53
Dec 25 07:54:57 ng-lt dnsmasq[4624]: using nameserver 10.200.0.245#53
Dec 25 07:54:57 ng-lt dnsmasq[4624]: read /etc/hosts - 3 addresses
Dec 25 07:54:57 ng-lt dnsmasq[4624]: read /var/lib/libvirt/dnsmasq/71b4-785d5195a1.addnhosts - 4 addresses
Dec 25 07:54:57 ng-lt dnsmasq-dhcp[4624]: read /var/lib/libvirt/dnsmasq/71b4-785d5195a1.hostsfile
Dec 25 07:54:57 ng-lt dnsmasq-dhcp[4624]: duplicate IP address 192.168.201.3 (lago_functional_tests_vm01) in dhcp-config directive
Dec 25 07:54:57 ng-lt dnsmasq-dhcp[4624]: duplicate IP address 192.168.201.2 (lago_functional_tests_vm02) in dhcp-config directive
Dec 25 07:54:57 ng-lt dnsmasq-dhcp[4624]: duplicate IP address fd8f:1391:3a82:5e0d::c0a8:c903 (lago_functional_tests_vm01) in dhcp-config directive
Dec 25 07:54:57 ng-lt dnsmasq-dhcp[4624]: duplicate IP address fd8f:1391:3a82:5e0d::c0a8:c902 (lago_functional_tests_vm02) in dhcp-config directive
Dec 25 07:55:13 ng-lt dnsmasq-dhcp[4624]: RTR-ADVERT(71b4-785d519) fd8f:1391:3a82:5e0d::
Dec 25 07:55:27 ng-lt dnsmasq-dhcp[4624]: RTR-ADVERT(71b4-785d519) fd8f:1391:3a82:5e0d::
Dec 25 07:55:33 ng-lt dnsmasq-dhcp[4624]: RTR-ADVERT(71b4-785d519) fd8f:1391:3a82:5e0d::
```
and after the reboot:

```
Dec 25 07:55:44 ng-lt dnsmasq-dhcp[4624]: DHCPDISCOVER(71b4-785d519) 54:52:c0:a8:c9:02
Dec 25 07:55:44 ng-lt dnsmasq-dhcp[4624]: DHCPOFFER(71b4-785d519) 192.168.201.2 54:52:c0:a8:c9:02
Dec 25 07:55:44 ng-lt dnsmasq-dhcp[4624]: DHCPREQUEST(71b4-785d519) 192.168.201.2 54:52:c0:a8:c9:02
Dec 25 07:55:44 ng-lt dnsmasq-dhcp[4624]: DHCPACK(71b4-785d519) 192.168.201.2 54:52:c0:a8:c9:02 lago_functional_tests_vm02
```

So I'm not sure yet why it is complaining about duplicate definitions(and we try to add 4 hosts), and also why rebooting the CirrOS VM resolves the issue.

**Comment by mykaul** [comment]
We need to ensure Lago is not creating those definitions - that it is not racy. I think the networks are not prepared in parallel (but worth checking).
I've opened a bug on libvirt that it seems to me that libvirt's dnsmasq config is sometimes not ready in time.

**Comment by nvgoldin** [comment]
@mykaul - will check. also need to check if the ``networkCreateXML`` call to libvirt is blocking, in the sense that it returns when completed.

for reference another failure: http://jenkins.ovirt.org/job/lago_master_check-merged-fc25-x86_64/3/console

**Comment by mykaul** [comment]
On Sun, Dec 25, 2016 at 3:30 PM, Nadav Goldin <notifications@github.com>
wrote:

> @mykaul <https://github.com/mykaul> - will check. also need to check if
> the networkCreateXML call to libvirt is blocking, in the sense that it
> returns when completed.
>

perhaps we should ask isActive() on it?

> for reference another failure: http://jenkins.ovirt.org/job/
> lago_master_check-merged-fc25-x86_64/3/console
>

Notice that I've found https://github.com/lago-project/lago/issues/402 and
fixed it in https://github.com/lago-project/lago/pull/404 (I hope). Perhaps
it can explain some of the issues.

**Comment by nvgoldin** [comment]
>perhaps we should ask isActive() on it?
exactly what I'm checking now..

is #404 ok to merge? we can try merging and see how others go.

**Comment by mykaul** [comment]
On Sun, Dec 25, 2016 at 4:00 PM, Nadav Goldin <notifications@github.com>
wrote:

> perhaps we should ask isActive() on it?
> exactly what I'm checking now..
>
> is #404 <https://github.com/lago-project/lago/pull/404> ok to merge? we
> can try merging and see how others go.
>

I sincerely hope so ;-)

**Comment by nvgoldin** [comment]
might have been resolved by https://github.com/lago-project/lago/pull/405, lets keep this ticket open for a while to see if it happens again in the following weeks.

**Comment by nvgoldin** [comment]
Unfortunately another failure:
http://jenkins.ovirt.org/job/lago_master_check-merged-fc25-x86_64/13/console
again restarting the network on the CirrOS VM resolved the issue. The difference here is that it was running on a bare-metal slave, which probably made things faster. So could be that the fix in #405, just gives more waiting time, but does not fix the issue.

**Comment by nvgoldin** [comment]
Moved the jobs back to VMs only for now.

**Comment by nvgoldin** [comment]
Finally got some true logs from the cirros vm on bootup:
```
Sending discover...

Sending discover...
Usage: /sbin/cirros-dhcpc <up|down>
No lease, failing
WARN: /etc/rc3.d/S40-network failed
```
For now I'm going to try add a work-around inside the image itself.

**Comment by mykaul** [comment]
Did you open a bug on cirros?

**Comment by nvgoldin** [comment]
> Did you open a bug on cirros?

Not sure if this is cirros bug, I need some more work to debug this on the libvirt/dnsmasq, I would suspect them for as I didn't see those dhcp request get to dnsmasq at all(only after restarting the network/dhcp).

**Comment by nvgoldin** [comment]
libvirt bug: https://bugzilla.redhat.com/show_bug.cgi?id=1411025

**Comment by nvgoldin** [comment]
Safe to say this was fixed with the cirros workaround., haven't seen it for a while.
